# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  - dev

pool:
  name: 'ERP_DEV'

jobs:
  - job: DotnetBuild
    steps: 
    - script: |
        export PATH=$PATH:/opt/dotnet6/
        cd aspnet-core/src/HRMv2.Migrator
        dotnet6 build
        dotnet6 publish
        cd bin/Debug/net6.0/publish/
        zip -r backend_migrator.zip *
      displayName: 'Dotnet Build Migrator'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'aspnet-core/src/HRMv2.Migrator/bin/Debug/net6.0/publish/backend_migrator.zip'
        ArtifactName: 'dev-dotnet-migrator-hrmv2'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts Migrator'

    - script: |
        export PATH=$PATH:/opt/dotnet6/
        cd aspnet-core
        dotnet6 build
        dotnet6 publish
        cd src/HRMv2.Web.Host/bin/Debug/net6.0/publish
        zip -r backend_publish.zip *
      displayName: 'Dotnet Build Host'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'aspnet-core/src/HRMv2.Web.Host/bin/Debug/net6.0/publish/backend_publish.zip'
        ArtifactName: 'dev-dotnet-host-hrmv2'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts Host'

  - job: AngularBuild
    steps:
      - script: |
          cd angular 
          export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
          nvm use 14.15
          node -v
          echo "===Install package==="
          npm i
        displayName: 'Install Package'

      - script: |
          export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
          nvm use 14.15
          cd angular
          echo "===Build node==="
          ng build --prod
        displayName: 'Build Frontend'

      - script: |
          export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
          nvm use 14.15
          cd angular/dist
          zip -r frontend_publish.zip *
        displayName: 'Compress Build'
        
        
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'angular/dist/frontend_publish.zip'
          ArtifactName: 'dev-fe-hrmv2'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts Frontend'