import {GetSalaryChangeRequestDto} from './GetSalaryChangeRequestDto'
export interface GetEmployeeSalaryChangeHistory{
    id: number,
    salaryChangeRequestId: number,
    employeeId: number,
    fromLevelId: number,
    levelName: string,
    toLevelId: number,
    toLevelName: string,
    fromUserTypeId: number,
    userTypeName: string,
    toUserTypeId: number,
    toUserTypeName: string,
    fromJobPositionId: number,
    jobPositionName: string,
    toJobPositionId: number,
    toJobPositionName: string,
    salary: number,
    toSalary: number,
    applyDate: string,
    note: string,
    type: number,
    updatedTime: string,
    updatedUser: string,
    hasContract: boolean,
    contractCode: string,
    salaryChangeRequest: GetSalaryChangeRequestDto,
    requestStatus: number
}