import { BadgeInfoDto } from "@shared/dto/user-infoDto"
import { BaseEmployeeDto } from "@shared/dto/user-infoDto"

export interface GetRequestEmployeeDto extends BaseEmployeeDto{
  id: number,
  fullName: string,
  email: string,
  sex: number,
  status: number,
  userTypeInfo: BadgeInfoDto,
  levelId: number,
  levelInfo: BadgeInfoDto,
  branchId: number,
  branchInfo: BadgeInfoDto,
  jobPositionId: number,
  jobPositionInfo: BadgeInfoDto,
  avatar: string,
  skills: Object,
  avatarFullPath: string,
  salaryChangeRequestId: number,
  employeeId: number,
  fromLevelId: number,
  levelName: string,
  toLevelId: number,
  toLevelName: string,
  fromUserType: number,
  userTypeName: string,
  toUserType: number,
  toUserTypeName: string,
  fromJobPositionId: number,
  jobPositionName: string,
  toJobPositionId: number,
  toJobPositionName: string,
  salary: number,
  toSalary: number,
  applyDate: string,
  note: string,
  type: number,
  requestStatus: number,
  updatedTime: string,
  updatedUser: string,
  typeName: string,
  statusName: string,
  contractEndDate: string,
  contractCode: string,
  hasContract: boolean,
  contractPeriod: number,
  fromUserTypeInfo: BadgeInfoDto,
  toUserTypeInfo: BadgeInfoDto
}
