export const PERMISSIONS_CONSTANT = {
    Home: 'Home',
    //Admin
    Admin: 'Admin',
    //User
    Admin_User: 'Admin.User',
    Admin_User_View: 'Admin.User.View',
    Admin_User_Create: 'Admin.User.Create',
    Admin_User_Edit: 'Admin.User.Edit',
    Admin_User_EditUserRole: 'Admin.User.EditUserRole',
    Admin_User_Delete: 'Admin.User.Delete',
    Admin_User_ResetPassword: 'Admin.User.ResetPassword',

    //Role
    Admin_Role: 'Admin.Role',
    Admin_Role_View: 'Admin.Role.View',
    Admin_Role_Create: 'Admin.Role.Create',
    Admin_Role_Edit: 'Admin.Role.Edit',
    Admin_Role_Delete: 'Admin.Role.Delete',

    //Tenant
    Admin_Tenant: 'Admin.Tenant',
    Admin_Tenant_View: 'Admin.Tenant.View',
    Admin_Tenant_Create: 'Admin.Tenant.Create',
    Admin_Tenant_Edit: 'Admin.Tenant.Edit',
    Admin_Tenant_Delete: 'Admin.Tenant.Delete',

    //Config
    Admin_Configuration: 'Admin.Configuration',
    Admin_Configuration_View: 'Admin.Configuration.View',
    Admin_Configuration_HRMSetting: 'Admin.Configuration.HRMSetting',
    Admin_Configuration_ProjectSetting: 'Admin.Configuration.ProjectSetting',
    Admin_Configuration_IMSSetting: 'Admin.Configuration.IMSSetting',
    Admin_Configuration_FinfastSetting: 'Admin.Configuration.FinfastSetting',
    Admin_Configuration_TimesheetSetting: 'Admin.Configuration.TimesheetSetting',
    Admin_Configuration_TalentSetting: 'Admin.Configuration.TalentSetting',
    Admin_Configuration_LoginSetting: 'Admin.Configuration.LoginSetting',
    Admin_Configuration_WokerAutoUpdateAllEmployeeInfo: 'Admin.Configuration.WokerAutoUpdateAllEmployeeInfo',
    Admin_Configuration_HRMSetting_View: 'Admin.Configuration.HRMSetting.View',
    Admin_Configuration_HRMSetting_Edit: 'Admin.Configuration.HRMSetting.Edit',
    Admin_Configuration_ProjectSettingView: 'Admin.Configuration.ProjectSetting.View',
    Admin_Configuration_IMSSetting_View: 'Admin.Configuration.IMSSetting.View',
    Admin_Configuration_FinfastSetting_View: 'Admin.Configuration.FinfastSetting.View',
    Admin_Configuration_TimesheetSetting_View: 'Admin.Configuration.TimesheetSetting.View',
    Admin_Configuration_TalentSetting_View: 'Admin.Configuration.TalentSetting.View',
    Admin_Configuration_LoginSetting_View: 'Admin.Configuration.LoginSetting.View',
    Admin_Configuration_LoginSetting_Edit: 'Admin.Configuration.LoginSetting.Edit',
    Admin_Configuration_WokerAutoUpdateAllEmployeeInfo_View: 'Admin.Configuration.WokerAutoUpdateAllEmployeeInfo.View',
    Admin_Configuration_WokerAutoUpdateAllEmployeeInfo_Edit: 'Admin.Configuration.WokerAutoUpdateAllEmployeeInfo.Edit',
    Admin_EmailTemplate: 'Admin.EmailTemplate',
    Admin_EmailTemplate_View: 'Admin.EmailTemplate.View',
    Admin_EmailTemplate_Edit: 'Admin.EmailTemplate.Edit',
    Admin_EmailTemplate_PreviewTemplate: 'Admin.EmailTemplate.PreviewTemplate',
    Admin_EmailTemplate_PreviewTemplate_SendMail: 'Admin.EmailTemplate.PreviewTemplate.SendMail',

    Admin_BackgroundJob: "Admin.BackgroundJob",
    Admin_BackgroundJob_View: "Admin.BackgroundJob.View",
    Admin_BackgroundJob_Delete: "Admin.BackgroundJob.Delete",
    Admin_BackgroundJob_Retry: "Admin.BackgroundJob.Retry",
    //Category
    Category: 'Category',
    //Branch
    Category_Branch: 'Category.Branch',
    Category_Branch_View: 'Category.Branch.View',
    Category_Branch_Create: 'Category.Branch.Create',
    Category_Branch_Edit: 'Category.Branch.Edit',
    Category_Branch_Delete: 'Category.Branch.Delete',
    //Usertype
    Category_Usertype: 'Category.Usertype',
    Category_Usertype_View: 'Category.Usertype.View',

    //JobPosition
    Category_JobPosition: 'Category.JobPosition',
    Category_JobPosition_View: 'Category.JobPosition.View',
    Category_JobPosition_Create: 'Category.JobPosition.Create',
    Category_JobPosition_Edit: 'Category.JobPosition.Edit',
    Category_JobPosition_Delete: 'Category.JobPosition.Delete',

    //Level
    Category_Level: 'Category.JobPosition',
    Category_Level_View: 'Category.Level.View',
    Category_Level_Create: 'Category.Level.Create',
    Category_Level_Edit: 'Category.Level.Edit',
    Category_Level_Delete: 'Category.Level.Delete',

    //Skill
    Category_Skill: 'Category.Skill',
    Category_Skill_View: 'Category.Skill.View',
    Category_Skill_Create: 'Category.Skill.Create',
    Category_Skill_Edit: 'Category.Skill.Edit',
    Category_Skill_Delete: 'Category.Skill.Delete',

    //Team
    Category_Team: 'Category.Team',
    Category_Team_View: 'Category.Team.View',
    Category_Team_Create: 'Category.Team.Create',
    Category_Team_Edit: 'Category.Team.Edit',
    Category_Team_Delete: 'Category.Team.Delete',

    //Bank
    Category_Bank: 'Category.Bank',
    Category_Bank_View: 'Category.Bank.View',
    Category_Bank_Create: 'Category.Bank.Create',
    Category_Bank_Edit: 'Category.Bank.Edit',
    Category_Bank_Delete: 'Category.Bank.Delete',

    //PunishmentType
    Category_PunishmentType: 'Category.PunishmentType',
    Category_PunishmentType_View: 'Category.PunishmentType.View',
    Category_PunishmentType_Create: 'Category.PunishmentType.Create',
    Category_PunishmentType_Edit: 'Category.PunishmentType.Edit',
    Category_PunishmentType_Delete: 'Category.PunishmentType.Delete',

    //IssuedBy
    Category_IssuedBy: 'Category.IssuedBy',
    Category_IssuedBy_View: 'Category.IssuedBy.View',
    Category_IssuedBy_Create: 'Category.IssuedBy.Create',
    Category_IssuedBy_Edit: 'Category.IssuedBy.Edit',
    Category_IssuedBy_Delete: 'Category.IssuedBy.Delete',

    //Punishment
    Punishment: 'Punishment',
    Punishment_View: 'Punishment.View',
    Punishment_Create: 'Punishment.Create',
    Punishment_Generate: 'Punishment.Generate',
    Punishment_Edit: 'Punishment.Edit',
    Punishment_Active: 'Punishment.Active',
    Punishment_Deactive: 'Punishment.Deactive',
    Punishment_Delete: 'Punishment.Delete',
    Punishment_PunishmentDetail: 'Punishment.PunishmentDetail',
    Punishment_PunishmentDetail_View: 'Punishment.PunishmentDetail.View',
    Punishment_PunishmentDetail_AddEmployee: 'Punishment.PunishmentDetail.AddEmployee',
    Punishment_PunishmentDetail_Edit: 'Punishment.PunishmentDetail.Edit',
    Punishment_PunishmentDetail_Delete: 'Punishment.PunishmentDetail.Delete',
    Punishment_PunishmentDetail_Import: 'Punishment.PunishmentDetail.Import',
    Punishment_PunishmentDetail_DownloadTemplate: 'Punishment.PunishmentDetail.DownloadTemplate',

    //PunishmentFund
    PunishmentFund : "PunishmentFund",
    PunishmentFund_View : "PunishmentFund.View",
    PunishmentFund_Add : "PunishmentFund.Add",
    PunishmentFund_Disburse : "PunishmentFund.Disburse",
    PunishmentFund_Edit : "PunishmentFund.Edit",
    PunishmentFund_Delete : "PunishmentFund.Delete",

    //Employee
    Employee: 'Employee',
    Employee_View: 'Employee.View',
    Employee_Create: 'Employee.Create',
    Employee_Edit: 'Employee.Edit',
    Employee_Delete: 'Employee.Delete',
    Employee_Export: 'Employee.Export',
    Employee_UploadAvatar: 'Employee.UploadAvatar',
    Employee_CreateEmployeeByFile: 'Employee.CreateEmployeeByFile',
    Employee_UpdateEmployeeByFile: 'Employee.UpdateEmployeeByFile',
    Employee_DownloadCreateTemplate: 'Employee.DownloadCreateTemplate',
    Employee_DownloadUpdateTemplate: 'Employee.DownloadUpdateTemplate',
    Employee_EmployeeDetail: 'Employee.EmployeeDetail',
    Employee_EmployeeDetail_TabPersonalInfo: 'Employee.EmployeeDetail.TabPersonalInfo',
    Employee_EmployeeDetail_TabPersonalInfo_View: 'Employee.EmployeeDetail.TabPersonalInfo.View',
    Employee_EmployeeDetail_TabPersonalInfo_Create: 'Employee.EmployeeDetail.TabPersonalInfo.Create',
    Employee_EmployeeDetail_TabPersonalInfo_SyncToOtherTool_ReCreateUserToOtherTool: 'Employee.EmployeeDetail.TabPersonalInfo.SyncToOtherTool.ReCreateUserToOtherTool',
    Employee_EmployeeDetail_TabPersonalInfo_SyncToOtherTool_QuitJobUserToOtherTool : 'Employee.EmployeeDetail.TabPersonalInfo.SyncToOtherTool.QuitJobUserToOtherTool',
    Employee_EmployeeDetail_TabPersonalInfo_SyncToOtherTool_EditUserToOtherTool: 'Employee.EmployeeDetail.TabPersonalInfo.SyncToOtherTool.EditUserToOtherTool',
    Employee_EmployeeDetail_TabPersonalInfo_SyncToOtherTool:'Employee.EmployeeDetail.TabPersonalInfo.SyncToOtherTool',
    Employee_EmployeeDetail_TabPersonalInfo_Edit: 'Employee.EmployeeDetail.TabPersonalInfo.Edit',
    Employee_EmployeeDetail_TabPersonalInfo_UploadAvatar: 'Employee.EmployeeDetail.TabPersonalInfo.UploadAvatar',
    Employee_EmployeeDetail_TabPersonalInfo_ChangeBranch: 'Employee.EmployeeDetail.TabPersonalInfo.ChangeBranch',
    Employee_EmployeeDetail_TabPersonalInfo_ChangeWorkingStatus: 'Employee.EmployeeDetail.TabPersonalInfo.ChangeWorkingStatus',
    Employee_EmployeeDetail_TabPersonalInfo_ChangeWorkingStatus_BackToWork: 'Employee.EmployeeDetail.TabPersonalInfo.ChangeWorkingStatus.BackToWork',
    Employee_EmployeeDetail_TabPersonalInfo_ChangeWorkingStatus_ExtendMaternityLeave: 'Employee.EmployeeDetail.TabPersonalInfo.ChangeWorkingStatus.ExtendMaternityLeave',
    Employee_EmployeeDetail_TabPersonalInfo_ChangeWorkingStatus_ExtendPausing: 'Employee.EmployeeDetail.TabPersonalInfo.ChangeWorkingStatus.ExtendPausing',
    Employee_EmployeeDetail_TabPersonalInfo_ChangeWorkingStatus_MaternityLeave: 'Employee.EmployeeDetail.TabPersonalInfo.ChangeWorkingStatus.MaternityLeave',
    Employee_EmployeeDetail_TabPersonalInfo_ChangeWorkingStatus_Pause: 'Employee.EmployeeDetail.TabPersonalInfo.ChangeWorkingStatus.Pause',
    Employee_EmployeeDetail_TabPersonalInfo_ChangeWorkingStatus_Quit: 'Employee.EmployeeDetail.TabPersonalInfo.ChangeWorkingStatus.Quit',

    Employee_EmployeeDetail_TabContract: 'Employee.EmployeeDetail.TabContract',
    Employee_EmployeeDetail_TabContract_View: 'Employee.EmployeeDetail.TabContract.View',
    Employee_EmployeeDetail_TabContract_ImportContractFile: 'Employee.EmployeeDetail.TabContract.ImportContractFile',
    Employee_EmployeeDetail_TabContract_EditNote: 'Employee.EmployeeDetail.TabContract.EditNote',
    Employee_EmployeeDetail_TabContract_Edit: 'Employee.EmployeeDetail.TabContract.Edit',
    Employee_EmployeeDetail_TabContract_DeleteContractFile: 'Employee.EmployeeDetail.TabContract.DeleteContractFile',
    Employee_EmployeeDetail_TabContract_Delete: 'Employee.EmployeeDetail.TabContract.Delete',
    Employee_EmployeeDetail_TabContract_PrintProbationaryContract: 'Employee.EmployeeDetail.TabContract.PrintProbationaryContract',
    Employee_EmployeeDetail_TabContract_PrintLaborContract: 'Employee.EmployeeDetail.TabContract.PrintLaborContract',
    Employee_EmployeeDetail_TabContract_PrintConfidentialContract: 'Employee.EmployeeDetail.TabContract.PrintConfidentialContract',
    Employee_EmployeeDetail_TabContract_PrintCollaboratorContract: 'Employee.EmployeeDetail.TabContract.PrintCollaboratorContract',
    Employee_EmployeeDetail_TabContract_PrintTrainingContract: 'Employee.EmployeeDetail.TabContract.PrintTrainingContract',

    Employee_EmployeeDetail_TabDebt: 'Employee.EmployeeDetail.TabDebt',
    Employee_EmployeeDetail_TabDebt_View: 'Employee.EmployeeDetail.TabDebt.View',
    Employee_EmployeeDetail_TabDebt_Add: 'Employee.EmployeeDetail.TabDebt.Add',

    Employee_EmployeeDetail_TabBenefit: 'Employee.EmployeeDetail.TabBenefit',
    Employee_EmployeeDetail_TabBenefit_View: 'Employee.EmployeeDetail.TabBenefit.View',
    Employee_EmployeeDetail_TabBenefit_Add: 'Employee.EmployeeDetail.TabBenefit.Add',
    Employee_EmployeeDetail_TabBenefit_Edit: 'Employee.EmployeeDetail.TabBenefit.Edit',
    Employee_EmployeeDetail_TabBenefit_Delete: 'Employee.EmployeeDetail.TabBenefit.Delete',

    Employee_EmployeeDetail_TabBonus: 'Employee.EmployeeDetail.TabBonus',
    Employee_EmployeeDetail_TabBonus_View: 'Employee.EmployeeDetail.TabBonus.View',
    Employee_EmployeeDetail_TabPunishment: 'Employee.EmployeeDetail.TabPunishment',
    Employee_EmployeeDetail_TabPunishment_View: 'Employee.EmployeeDetail.TabPunishment.View',

    Employee_EmployeeDetail_TabSalaryHistory: 'Employee.EmployeeDetail.TabSalaryHistory',
    Employee_EmployeeDetail_TabSalaryHistory_View: 'Employee.EmployeeDetail.TabSalaryHistory.View',
    Employee_EmployeeDetail_TabSalaryHistory_EditNote: 'Employee.EmployeeDetail.TabSalaryHistory.EditNote',
    Employee_EmployeeDetail_TabSalaryHistory_Edit: 'Employee.EmployeeDetail.TabSalaryHistory.Edit',
    Employee_EmployeeDetail_TabSalaryHistory_Delete: 'Employee.EmployeeDetail.TabSalaryHistory.Delete',
    Employee_EmployeeDetail_TabSalaryHistory_ForceDelete: 'Employee.EmployeeDetail.TabSalaryHistory.ForceDelete',
    Employee_EmployeeDetail_TabWorkingHistory: 'Employee.EmployeeDetail.TabWorkingHistory',
    Employee_EmployeeDetail_TabWorkingHistory_View: 'Employee.EmployeeDetail.TabWorkingHistory.View',
    Employee_EmployeeDetail_TabWorkingHistory_EditNote: 'Employee.EmployeeDetail.TabWorkingHistory.EditNote',
    Employee_EmployeeDetail_TabWorkingHistory_EditDate: 'Employee.EmployeeDetail.TabWorkingHistory.EditDate',
    Employee_EmployeeDetail_TabWorkingHistory_Delete: 'Employee.EmployeeDetail.TabWorkingHistory.Delete',
    Employee_EmployeeDetail_TabBranchHistory: 'Employee.EmployeeDetail.TabBranchHistory',
    Employee_EmployeeDetail_TabBranchHistory_View: 'Employee.EmployeeDetail.TabBranchHistory.View',
    Employee_EmployeeDetail_TabBranchHistory_EditNote: 'Employee.EmployeeDetail.TabBranchHistory.EditNote',
    Employee_EmployeeDetail_TabBranchHistory_Delete: 'Employee.EmployeeDetail.TabBranchHistory.Delete',
    Employee_EmployeeDetail_TabPayslipHistory: 'Employee.EmployeeDetail.TabPayslipHistory',
    Employee_EmployeeDetail_TabPayslipHistory_View: 'Employee.EmployeeDetail.TabPayslipHistory.View',

    //WarningEmployee
    WarningEmployee: 'WarningEmployee',
    WarningEmployee_BackToWork: 'WarningEmployee.BackToWork',
    WarningEmployee_BackToWork_View: 'WarningEmployee.BackToWork.View',
    WarningEmployee_BackToWork_UpdateEmployeeBackDate: 'WarningEmployee.BackToWork.UpdateEmployeeBackDate',
    WarningEmployee_BackToWork_BackToWork: 'WarningEmployee.BackToWork.BackToWork',
    WarningEmployee_ContractExpired: 'WarningEmployee.ContractExpired',
    WarningEmployee_ContractExpired_View: 'WarningEmployee.ContractExpired.View',
    WarningEmployee_TempEmployeeTS: "WarningEmployee.RequestChangeInfo",
    WarningEmployee_RequestChangeInfo_View: "WarningEmployee.RequestChangeInfo",
    WarningEmployee_RequestChangeInfo_DetailRequest: "WarningEmployee.RequestChangeInfo",
    WarningEmployee_RequestChangeInfo_DetailRequest_View: "WarningEmployee.RequestChangeInfo",
    WarningEmployee_RequestChangeInfo_DetailRequest_Approve: "WarningEmployee.RequestChangeInfo.DetailRequest.Approve",
    WarningEmployee_RequestChangeInfo_DetailRequest_Reject: "WarningEmployee.RequestChangeInfo.DetailRequest.Reject",
    WarningEmployee_PlanOnboard: "WarningEmployee.PlanOnboard",
    WarningEmployee_PlanOnboard_View: "WarningEmployee.PlanOnboard.View",
    WarningEmployee_PlanOnboard_Create: "WarningEmployee.PlanOnboard.Create",
    WarningEmployee_PlanOnboard_Edit: "WarningEmployee.PlanOnboard.Edit",
    WarningEmployee_PlanOnboard_Delete: "WarningEmployee.PlanOnboard.Delete",
    WarningEmployee_PlanOnboard_ViewSalary : "WarningEmployee.PlanOnboard.ViewSalary",
    WarningEmployee_PlanQuitEmployee: "WarningEmployee.PlanQuitEmployee",
    WarningEmployee_PlanQuitEmployee_View: "WarningEmployee.PlanQuitEmployee.View",
    WarningEmployee_PlanQuitEmployee_Edit: "WarningEmployee.PlanQuitEmployee.Edit",
    WarningEmployee_PlanQuitEmployee_Detele: "WarningEmployee.PlanQuitEmployee.Detele",

    //Debt
    Debt: 'Debt',
    Debt_View: 'Debt.View',
    Debt_Create: 'Debt.Create',
    Debt_Delete: 'Debt.Delete',
    Debt_DebtDetail: 'Debt.DebtDetail',
    Debt_DebtDetail_Edit: 'Debt.DebtDetail.Edit',
    Debt_DebtDetail_Delete: 'Debt.DebtDetail.Delete',
    Debt_DebtDetail_SetDone: 'Debt.DebtDetail.SetDone',
    Debt_DebtDetail_GeneratePaymentPlan: 'Debt.DebtDetail.GeneratePaymentPlan',
    Debt_DebtDetail_AddPaymentPlan: 'Debt.DebtDetail.AddPaymentPlan',
    Debt_DebtDetail_EditPaymentPlan: 'Debt.DebtDetail.EditPaymentPlan',
    Debt_DebtDetail_DeletePaymentPlan: 'Debt.DebtDetail.DeletePaymentPlan',
    Debt_DebtDetail_AddDebtPaid: 'Debt.DebtDetail.AddDebtPaid',
    Debt_DebtDetail_EditDebtPaid: 'Debt.DebtDetail.EditDebtPaid',
    Debt_DebtDetail_DeleteDebtPaid: 'Debt.DebtDetail.DeleteDebtPaid',

    Refund: "Refund",
    Refund_View: "Refund.View",
    Refund_Create: "Refund.Create",
    Refund_Edit: "Refund.Edit",
    Refund_Active: "Refund.Active",
    Refund_Deactive: "Refund.Deactive",
    Refund_Delete: "Refund.Delete",
    Refund_RefundDetail: "Refund.RefundDetai",
    Refund_RefundDetail_View: "Refund.RefundDetai.View",
    Refund_RefundDetail_AddEmployee: "Refund.RefundDetai.AddEmployee",
    Refund_RefundDetail_Edit: "Refund.RefundDetai.Edit",
    Refund_RefundDetail_Delete: "Refund.RefundDetai.Delete",

    //Bonus
    Bonus: 'Bonus',
    Bonus_View: 'Bonus.View',
    Bonus_Create: 'Bonus.Create',
    Bonus_Edit: 'Bonus.Edit',
    Bonus_Active: 'Bonus.Active',
    Bonus_Deactive: 'Bonus.Deactive',
    Bonus_Delete: 'Bonus.Delete',
    Bonus_BonusDetail: 'Bonus.BonusDetail',
    Bonus_BonusDetail_TabInformation: 'Bonus.BonusDetail.TabInformation',
    Bonus_BonusDetail_TabInformation_View: 'Bonus.BonusDetail.TabInformation.View',
    Bonus_BonusDetail_TabInformation_Edit: 'Bonus.BonusDetail.TabInformation.Edit',
    Bonus_BonusDetail_TabEmployee: 'Bonus.BonusDetail.TabEmployee',
    Bonus_BonusDetail_TabEmployee_View: 'Bonus.BonusDetail.TabEmployee.View',
    Bonus_BonusDetail_TabEmployee_Add: 'Bonus.BonusDetail.TabEmployee.Add',
    Bonus_BonusDetail_TabEmployee_QuickAdd: 'Bonus.BonusDetail.TabEmployee.QuickAdd',
    Bonus_BonusDetail_TabEmployee_Import: 'Bonus.BonusDetail.TabEmployee.Import',
    Bonus_BonusDetail_TabEmployee_Edit: 'Bonus.BonusDetail.TabEmployee.Edit',
    Bonus_BonusDetail_TabEmployee_Delete: 'Bonus.BonusDetail.TabEmployee.Delete',
    Bonus_BonusDetail_TabEmployee_DownloadTemplate: 'Bonus.BonusDetail.TabEmployee.DownloadTemplate',
    Bonus_BonusDetail_TabEmployee_SendAllMail : "Bonus.BonusDetail.TabEmployee.SendAllMail",
    Bonus_BonusDetail_TabEmployee_SendMail : "Bonus.BonusDetail.TabEmployee.SendMail",

    //Benefit
    Benefit: 'Benefit',
    Benefit_View: 'Benefit.View',
    Benefit_Create: 'Benefit.Create',
    Benefit_Edit: 'Benefit.Edit',
    Benefit_Active: 'Benefit.Active',
    Benefit_Deactive: 'Benefit.Deactive',
    Benefit_Delete: 'Benefit.Delete',
    Benefit_BenefitDetail: 'Benefit.BenefitDetail',
    Benefit_BenefitDetail_TabInformation: 'Benefit.BenefitDetail.TabInformation',
    Benefit_BenefitDetail_TabInformation_View: 'Benefit.BenefitDetail.TabInformation.View',
    Benefit_BenefitDetail_TabInformation_Edit: 'Benefit.BenefitDetail.TabInformation.Edit',
    Benefit_BenefitDetail_TabInformation_Delete: 'Benefit.BenefitDetail.TabInformation.Delete',
    Benefit_BenefitDetail_TabInformation_Clone: 'Benefit.BenefitDetail.TabInformation.Clone',
    Benefit_BenefitDetail_TabEmployee: 'Benefit.BenefitDetail.TabEmployee',
    Benefit_BenefitDetail_TabEmployee_View: 'Benefit.BenefitDetail.TabEmployee.View',
    Benefit_BenefitDetail_TabEmployee_Add: 'Benefit.BenefitDetail.TabEmployee.Add',
    Benefit_BenefitDetail_TabEmployee_QuickAdd: 'Benefit.BenefitDetail.TabEmployee.QuickAdd',
    Benefit_BenefitDetail_TabEmployee_Edit: 'Benefit.BenefitDetail.TabEmployee.Edit',
    Benefit_BenefitDetail_TabEmployee_Delete: 'Benefit.BenefitDetail.TabEmployee.Delete',
    Benefit_BenefitDetail_TabEmployee_UpdateAllStartDate: 'Benefit.BenefitDetail.TabEmployee.UpdateAllStartDate',
    Benefit_BenefitDetail_TabEmployee_UpdateAllEndDate: 'Benefit.BenefitDetail.TabEmployee.UpdateAllEndDate',

    //Payroll
    Payroll: 'Payroll',
    Payrol_View: 'Payroll.View',
    Payroll_Create: 'Payroll.Create',
    Payroll_Edit: 'Payroll.Edit',
    Payroll_Delete: 'Payroll.Delete',
    Payroll_SendToAccountant: 'Payroll.SendToAccountant',
    Payrol_ApproveAndSendtToCEO: 'Payroll.ApproveAndSendtToCEO',
    Payroll_RejectByKT: 'Payroll.RejectByKT',
    Payroll_ApproveByKT: 'Payroll.ApproveByKT',
    Payroll_RejectByCEO: 'Payroll.RejectByCEO',
    Payroll_ApproveByCEO: 'Payroll.ApproveByCEO',
    Payroll_Execute: 'Payroll.Execute',
    Payroll_Payslip: 'Payroll.Payslip',
    Payroll_Payslip_View: 'Payroll.Payslip.View',
    Payroll_Payslip_CalculateSalary: 'Payroll.Payslip.CalculateSalary',
    Payroll_Payslip_SendMailAll: 'Payroll.Payslip.SendMailAll',
    Payroll_Payslip_Add: 'Payroll.Payslip.Add',
    Payroll_Payslip_Export: 'Payroll.Payslip.Export',
    Payroll_Payslip_Delete: 'Payroll.Payslip.Delete',
    Payroll_Payslip_SendMail: 'Payroll.Payslip.SendMail',
    Payroll_Payslip_SendToAccountant: 'Payroll.Payslip.SendToAccountant',
    Payroll_Payslip_ApproveAndSendtToCEO: 'Payroll.Payslip.ApproveAndSendtToCEO',
    Payroll_Payslip_RejectByKT: 'Payroll.Payslip.RejectByKT',
    Payroll_Payslip_ApproveByKT: 'Payroll.Payslip.ApproveByKT',
    Payroll_Payslip_RejectByCEO: 'Payroll.Payslip.RejectByCEO',
    Payroll_Payslip_ApproveByCEO: 'Payroll.Payslip.ApproveByCEO',
    Payroll_Payslip_Execute: 'Payroll.Payslip.Execute',
    Payroll_Payslip_DownloadTemplateUpdateRemainLeaveDaysAfter: "Payroll.Payslip.DownloadTemplateUpdateRemainLeaveDaysAfter",
    Payroll_Payslip_UpdateRemainLeaveDaysAfter: "Payroll.Payslip.UpdateRemainLeaveDaysAfter",
    Payroll_Payslip_ExportPayrollIncludeLastMonth : "Payroll.Payslip.ExportPayrollIncludeLastMonth",
    Payroll_Payslip_ExportPayroll: "Payroll.Payslip.ExportPayroll",
    Payroll_Payslip_ExportOutsideTech: "Payroll.Payslip.ExportOutsideTech",
    Payroll_Payslip_ExportTechcombank: "Payroll.Payslip.ExportTechcombank",
    Payroll_Payslip_UpdatePayslipDeadline: "Payroll.Payslip.UpdatePayslipDeadline",
    Payroll_Payslip_PayslipDetail: 'Payroll.Payslip.PayslipDetail',
    Payroll_Payslip_PayslipDetail_TabSalary: 'Payroll.Payslip.PayslipDetail.TabSalary',
    Payroll_Payslip_PayslipDetail_TabSalary_View: 'Payroll.Payslip.PayslipDetail.TabSalary.View',
    Payroll_Payslip_PayslipDetail_TabSalary_CollectAndReCalculateSalary: 'Payroll.Payslip.PayslipDetail.TabSalary.CollectAndReCalculateSalary',
    Payroll_Payslip_PayslipDetail_TabSalary_ReCalculateSalary: 'Payroll.Payslip.PayslipDetail.TabSalary.ReCalculateSalary',
    Payroll_Payslip_PayslipDetail_TabSalary_UpdatePayslipDetails: 'Payroll.Payslip.PayslipDetail.TabSalary.UpdatePayslipDetails',
    Payroll_Payslip_PayslipDetail_TabDebt: 'Payroll.Payslip.PayslipDetail.TabDebt',
    Payroll_Payslip_PayslipDetail_TabDebt_View: 'Payroll.Payslip.PayslipDetail.TabDebt.View',
    Payroll_Payslip_PayslipDetail_TabBenefit: 'Payroll.Payslip.PayslipDetail.TabBenefit',
    Payroll_Payslip_PayslipDetail_TabBenefit_View: 'Payroll.Payslip.PayslipDetail.TabBenefit.View',
    Payroll_Payslip_PayslipDetail_TabBonus: 'Payroll.Payslip.PayslipDetail.TabBonus',
    Payroll_Payslip_PayslipDetail_TabBonus_View: 'Payroll.Payslip.PayslipDetail.TabBonus.View',
    Payroll_Payslip_PayslipDetail_TabBonus_Add: 'Payroll.Payslip.PayslipDetail.TabBonus.Add',
    Payroll_Payslip_PayslipDetail_TabBonus_Edit: 'Payroll.Payslip.PayslipDetail.TabBonus.Edit',
    Payroll_Payslip_PayslipDetail_TabBonus_Delete: 'Payroll.Payslip.PayslipDetail.TabBonus.Delete',
    Payroll_Payslip_PayslipDetail_TabPunishment: 'Payroll.Payslip.PayslipDetail.TabPunishment',
    Payroll_Payslip_PayslipDetail_TabPunishment_View: 'Payroll.Payslip.PayslipDetail.TabPunishment.View',
    Payroll_Payslip_PayslipDetail_TabPunishment_Add: 'Payroll.Payslip.PayslipDetail.TabPunishment.Add',
    Payroll_Payslip_PayslipDetail_TabPunishment_Edit: 'Payroll.Payslip.PayslipDetail.TabPunishment.Edit',
    Payroll_Payslip_PayslipDetail_TabPunishment_Delete: 'Payroll.Payslip.PayslipDetail.TabPunishment.Delete',
    Payroll_Payslip_PayslipDetail_TabPayslipPreview: 'Payroll.Payslip.PayslipDetail.TabPayslipPreview',
    Payroll_Payslip_PayslipDetail_TabPayslipPreview_View: 'Payroll.Payslip.PayslipDetail.TabPayslipPreview.View',

    //SalaryChangeRequest
    SalaryChangeRequest: 'SalaryChangeRequest',
    SalaryChangeRequest_View: 'SalaryChangeRequest.View',
    SalaryChangeRequest_Create: 'SalaryChangeRequest.Create',
    SalaryChangeRequest_Edit: 'SalaryChangeRequest.Edit',
    SalaryChangeRequest_Delete: 'SalaryChangeRequest.Delete',
    SalaryChangeRequest_Send: 'SalaryChangeRequest.Send',
    SalaryChangeRequest_Approve: 'SalaryChangeRequest.Approve',
    SalaryChangeRequest_Reject: 'SalaryChangeRequest.Reject',
    SalaryChangeRequest_Execute: 'SalaryChangeRequest.Execute',
    SalaryChangeRequest_SalaryChangeRequestDetail: 'SalaryChangeRequest.SalaryChangeRequestDetail',
    SalaryChangeRequest_SalaryChangeRequestDetail_View: 'SalaryChangeRequest.SalaryChangeRequestDetail.View',
    SalaryChangeRequest_SalaryChangeRequestDetail_Add: 'SalaryChangeRequest.SalaryChangeRequestDetail.Add',
    SalaryChangeRequest_SalaryChangeRequestDetail_Delete: 'SalaryChangeRequest.SalaryChangeRequestDetail.Delete',
    SalaryChangeRequest_SalaryChangeRequestDetail_Send: 'SalaryChangeRequest.SalaryChangeRequestDetail.Send',
    SalaryChangeRequest_SalaryChangeRequestDetail_Approve: 'SalaryChangeRequest.SalaryChangeRequestDetail.Approve',
    SalaryChangeRequest_SalaryChangeRequestDetail_Reject: 'SalaryChangeRequest.SalaryChangeRequestDetail.Reject',
    SalaryChangeRequest_SalaryChangeRequestDetail_Execute: 'SalaryChangeRequest.SalaryChangeRequestDetail.Execute',
    SalaryChangeRequest_SalaryChangeRequestDetail_SendAllMail : 'SalaryChangeRequest.SalaryChangeRequestDetail.SenAllMail',
    SalaryChangeRequest_SalaryChangeRequestDetail_SendMail : "SalaryChangeRequest.SalaryChangeRequestDetail.SendMail",
    SalaryChangeRequest_SalaryChangeRequestDetail_DownloadTemplate : "SalaryChangeRequest.SalaryChangeRequestDetail.DownloadTemplate",
    SalaryChangeRequest_SalaryChangeRequestDetail_ImportCheckpoint : "SalaryChangeRequest.SalaryChangeRequestDetail.ImportCheckpoint",
    SalaryChangeRequest_SalaryChangeRequestDetail_SalaryChangeRequestEmployeeDetail: 'SalaryChangeRequest.SalaryChangeRequestDetail.SalaryChangeRequestEmployeeDetail',
    SalaryChangeRequest_SalaryChangeRequestDetail_SalaryChangeRequestEmployeeDetail_View: 'SalaryChangeRequest.SalaryChangeRequestDetail.SalaryChangeRequestEmployeeDetail.View',
    SalaryChangeRequest_SalaryChangeRequestDetail_SalaryChangeRequestEmployeeDetail_Edit: 'SalaryChangeRequest.SalaryChangeRequestDetail.SalaryChangeRequestEmployeeDetail.Edit',
    SalaryChangeRequest_SalaryChangeRequestDetail_SalaryChangeRequestEmployeeDetail_UploadContractFile: 'SalaryChangeRequest.SalaryChangeRequestDetail.SalaryChangeRequestEmployeeDetail.UploadContractFile',
    SalaryChangeRequest_SalaryChangeRequestDetail_SalaryChangeRequestEmployeeDetail_DeleteContractFile: 'SalaryChangeRequest.SalaryChangeRequestDetail.SalaryChangeRequestEmployeeDetail.DeleteContractFile'











};
