using Amazon.Runtime.Internal.Transform;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HRMv2.Utils
{
    public class AuditLogUtils
    {
        public static Dictionary<string, string> Dict = new Dictionary<string, string>() {
            {"HRMv2.APIs.DebtPaymentPlans.DebtPaymentPlanAppService GetAll", "Trang Debt" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetListMonthFilterOfEmployee", "Trang Bonus" },
            {"HRMv2.APIs.Payslips.PayslipAppService GetEmployeeIdsInPayroll", "Trang Payroll"},
            {"HRMv2.APIs.Payslips.PayslipAppService GetPayslipResult", "Trang Payroll" },
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService GetLaborContractTemplate" , "Trang Employee > Contract Expired"},
            {"HRMv2.APIs.Bonuses.BonusAppService GetAllEmployeeInBonus", "Trang Bonus" },
            {"HRMv2.APIs.DebtPaids.DebtPaidAppService GetPaidsByDebtId", "Trang Debt" },
            {"HRMv2.APIs.Banks.BankAppService GetAll", "Trang Category > Bank" },
            {"HRMv2.APIs.Histories.HistoryAppService GetEmployeeWorkingHistoryByTimeSpan", "Trang Punishment" },
            {"HRMv2.APIs.Payrolls.PayrollAppService Get", "Trang Payroll" },
            {"HRMv2.APIs.Debts.DebtAppService Get", "Trang Debt" },
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService GetAllPaging", "Trang Salary change request" },
            {"HRMv2.Configuration.ConfigurationAppService GetDiscordChannels", "Trang Admin > Configuration" },
            {"HRMv2.APIs.Payslips.PayslipAppService GetComparePayslipPaging", "Trang Payroll" },
            {"HRMv2.APIs.Branchs.BranchAppService GetAll", "Trang Category > Branches" },
            {"HRMv2.Configuration.ConfigurationAppService GetConnectResult", "Trang Admin > Configuration" },
            {"HRMv2.APIs.Refunds.RefundAppService GetAllPaging", "Trang Refund" },
            {"HRMv2.APIs.UserTypes.UserTypeAppService GetAll", "Trang Admin > User" },
            {"HRMv2.APIs.Timesheet.TimesheetAppService GetAllInsuranceStatuses", "Timesheet" },
            {"HRMv2.Roles.RoleAppService GetAllAsync", "Trang Admin > Role" },
            {"HRMv2.Users.UserAppService GetRoles", "Trang Admin > User" },
            {"HRMv2.Roles.RoleAppService GetRoleForEdit", "Trang Admin > Role" },
            {"Abp.AspNetCore.Mvc.Controllers.AbpUserConfigurationController GetAll", "Trang Admin > User" },
            {"HRMv2.APIs.Benefits.BenefitAppService GetAllPaging", "Trang Benefit" },
            {"HRMv2.APIs.Benefits.BenefitAppService GetEmployeeInBenefit", "Trang Benefit" },
            {"HRMv2.APIs.Benefits.BenefitAppService GetAllEmployeeNotInBenefit", "Trang Benefit" },
            {"HRMv2.APIs.ChangeEmployeeWorkingStatus.ChangeEmployeeWorkingStatusAppService GetLatestSalaryChangeRequest", "Trang Salary change request" },
            {"HRMv2.APIs.Debts.DebtAppService GetAllPaging", "Trang Debt" },
            {"HRMv2.APIs.BackgroundJobs.BackgroundJobAppService GetAllPaging", "Trang Admin > Background Job" },
            {"HRMv2.APIs.JobPositions.JobPositionAppService GetAllPaging", "Trang Category > Job Position" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetAllEmployeeNotInPunishment", "Trang Punishment" },
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService GetListDateFromSalaryRequest", "Trang Salary change request" },
            {"HRMv2.APIs.Benefits.BenefitAppService GetBenefitByEmployeeId", "Trang Benefit" },
            {"HRMv2.APIs.Histories.HistoryAppService GetAllEmployeePayslipHistory", "Trang Payroll" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetListMonthFilter", "Trang Bonus" },
            {"HRMv2.APIs.JobPositions.JobPositionAppService GetAll", "Trang Category > Job Position" },
            {"HRMv2.APIs.Histories.HistoryAppService GetAllEmployeeBranchHistory", "Trang Category > Branch" },
            {"HRMv2.APIs.Refunds.RefundAppService GetRefundEmployeesPaging", "Trang Refund" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetAllPunishmentForPayslipEmployee", "Trang Punishment" },
            {"HRMv2.APIs.PunishmentTypes.PunishmentTypeAppService GetAllPaging", "Trang Category > Punishment Type" },
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService GetAllEmployeesBackToWork", "Trang Warning Employee > Back to work" },
            {"HRMv2.APIs.Employees.EmployeeAppService GetDataMetaToCreateEmployeeByFile1", "Trang Employee" },
            {"HRMv2.APIs.Branchs.BranchAppService GetAllPaging", "Trang Category > Branch" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetAllPagingBonusesByEmployeeId", "Trang Bonus" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetAllEmployeeInPunishment", "Trang Punishment" },
            {"HRMv2.APIs.Employees.EmployeeAppService GetDataMetaToUpdateEmployeeByFile", "Trang Employee" },
            {"HRMv2.APIs.EmailTemplates.EmailTemplateAppService GetAll", "Trang Admin >Email template" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetDateFromPunishmentsOfEmployee", "Trang Punishment" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetAllPunishmentToAddPayslip", "Trang Punishment" },
            {"HRMv2.APIs.Debts.DebtAppService GetByEmployeeId", "Trang Debt" },
            {"HRMv2.APIs.EmailTemplates.EmailTemplateAppService GetTemplateById", "Trang Admin > Email template" },
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService GetAllEmployeesToUpdateContract", "Trang Warning Employee > Contract Expired" },
            {"HRMv2.APIs.Benefits.BenefitAppService Get", "Trang Benefit" },
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService GetAllPaging", "Trang Warning Employee > Contract Expired" },
            {"HRMv2.APIs.Refunds.RefundAppService GetAllEmployeeNotInRefund", "Trang Refund" },
            {"HRMv2.APIs.Home.HomeAppService GetAllWorkingHistory", "Trang Home page" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetAllPaging", "Trang Bonus" },
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService GetEmployeeNotInRequest", "Trang Salary change request" },
            {"HRMv2.APIs.Employees.EmployeeAppService GetEmployeeBasicInfoForBreadcrumb", "Trang Employee" },
            {"HRMv2.APIs.Payslips.PayslipAppService GetPayslipDetailByType", "Trang Payroll" },
            {"HRMv2.APIs.Payrolls.PayrollAppService GetListDateFromPayroll", "Trang Payroll" },
            {"HRMv2.APIs.Debts.DebtAppService GetDebtTemplate", "Trang Debt" },
            {"HRMv2.Configuration.ConfigurationAppService GetLoginSetting", "Trang Admin > Configuration" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetBonusTemplate", "Bonus" },
            {"HRMv2.APIs.Payslips.PayslipAppService GetPayslipDetail", "Trang Payroll" },
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService GetRequestUpdateInfo", "Trang Warning Employee > Request Change Info" },
            {"HRMv2.APIs.Refunds.RefundAppService GetListMonthsForCreate", "Trang Refund" },
            {"HRMv2.APIs.Payslips.PayslipAppService GetEmailTemplate", "Trang Payroll" },
            {"HRMv2.Configuration.ConfigurationAppService GetEmailSetting", "Trang Admin > Configuration" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetAllBonusEmployee","Trang Bonus" },
            {"HRMv2.APIs.CheckIn.CheckInAppService GetUserForCheckIn", "CheckIn" },
            {"HRMv2.APIs.Publics.PublicAppService GetFundCurrentBalance", "PublicAppService" },
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService GetTempEmployeeTalentById", "Trang Warning Employee > Plan Onboard Employee" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetAllPaging", "Trang Punishment" },
            {"HRMv2.APIs.Refunds.RefundAppService GetListRefundDate", "Trang Refund" },
            {"HRMv2.APIs.Publics.PublicAppService GetFunAmountHistories", "PublishAppService" },
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService GetEmployeesInSalaryRequest", "Trang Salary change request" },
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService GetCheckpointTemplate", "Trang Salary change request" },
            {"HRMv2.APIs.Payrolls.PayrollAppService GetAllPaging", "Trang Payroll" },
            {"HRMv2.APIs.Skills.SkillAppService GetAllPaging", "Trang Category > Skill" },
            {"HRMv2.Users.UserAppService GetAllAsync", "Trang Admin > User" },
            {"HRMv2.APIs.PunishmentTypes.PunishmentTypeAppService GetAll", "Trang Category > Punishment Type" },
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService Get", "Trang Salary change request" },
            {"HRMv2.Roles.RoleAppService GetAllUserNotInRole", "Trang Admin > Role" },
            {"HRMv2.APIs.Banks.BankAppService GetAllPaging", "Trang Category > Bank" },
            {"HRMv2.Roles.RoleAppService GetAllPermissions", "Trang Admin > Role" },
            {"HRMv2.APIs.Employees.EmployeeAppService GetAll", "Trang Employee" },
            {"HRMv2.APIs.Teams.TeamAppService GetAll", "Trang Category > Team" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetPunishmentById", "Trang Punishment" },
            {"HRMv2.APIs.Refunds.RefundAppService Get", "Trang Refund" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetAllEmployeeNotInBonus", "Trang Bonus" },
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService GetContractTemplate", "Trang Warning Employee > Contract Expired" },
            {"HRMv2.APIs.Timesheet.TimesheetAppService GetUserInfoByEmail", "Timesheet" },
            {"HRMv2.APIs.Payslips.PayslipAppService GetPayslipLastMonth", "Trang Payroll" },
            {"HRMv2.APIs.Benefits.BenefitAppService GetListEmployeeIdInBenefit", "Trang Benefit" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetDateFromPunishments", "Trang Punishment" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetMonthlyPunishmentByEmployeeId", "Trang Punishment" },
            {"HRMv2.APIs.Employees.EmployeeAppService GetDataMetaToCreateEmployeeByFile", "Trang Employee" },
            {"HRMv2.APIs.Benefits.BenefitAppService GetAll", "Trang Benefit" },
            {"HRMv2.MultiTenancy.TenantAppService GetAsync", "Trang Admin > Tenant" },
            {"HRMv2.Configuration.ConfigurationAppService GetAllSetting", "Trang Admin > Configuration" },
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService GetAll", "Trang Warning Employee > Contract Expired" },
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService GetRequestEmployeeById", "Trang Salary change Request" },
            {"HRMv2.MultiTenancy.TenantAppService GetAllAsync", "Trang Admin > Tenant" },
            {"HRMv2.APIs.Benefits.BenefitAppService GetListMonthFilter", "Trang Benefit" },
            {"HRMv2.APIs.Teams.TeamAppService GetAllPaging", "Trang Category > Team" },
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService GetRequestDetailById", "Trang Warning Employee > Request Change Info" },
            {"HRMv2.APIs.Timesheet.TimesheetAppService GetInfoToUpdate", "Timesheet" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetAll", "Trang Punishment" },
            {"HRMv2.APIs.Refunds.RefundAppService GetAll", "Trang Refund" },
            {"HRMv2.APIs.Payslips.PayslipAppService GetSumaryInfomation", "Trang Payroll" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetPunishmentByEmployeeId", "Trang Punishment" },
            {"HRMv2.APIs.Levels.LevelAppService GetAll", "Trang Category > Level" },
            {"HRMv2.APIs.Histories.HistoryAppService GetAllEmployeeSalaryHistory", "Trang Employee" },
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService GetTemplateToImportCheckpoint", "Trang Salary change request" },
            {"HRMv2.APIs.Payslips.PayslipAppService GetPayslipEmployeePaging", "Trang Payroll" },
            {"HRMv2.APIs.Histories.HistoryAppService GetAllEmployeeWorkingHistory", "Trang Employee" },
            {"HRMv2.APIs.DebtPaymentPlans.DebtPaymentPlanAppService Get", "Trang Debt" },
            {"HRMv2.APIs.DebtPaymentPlans.DebtPaymentPlanAppService GetPaymentPlansByDebId", "Trang Debt" },
            {"HRMv2.APIs.Employees.EmployeeAppService Get", "Trang Employee" },
            {"HRMv2.APIs.Publics.PublicAppService GetEmployeePhone", "PublishAppService" },
            {"HRMv2.APIs.Publics.PublicAppService GetPhoneNumberByEmail", "PublishAppService" },
            {"HRMv2.Roles.RoleAppService GetAllUserInRole", "Trang Admin > Role" },
            {"HRMv2.APIs.Employees.EmployeeAppService GetAllEmployeeBasicInfo", "Trang Employee" },
            {"HRMv2.APIs.Employees.EmployeeAppService GetEmployeeExcept", "Trang Employee" },
            {"HRMv2.APIs.AuditLogs.AuditLogAppService GetAllEmailAddressInAuditLog", "Trang Admin > AuditLogs" },
            {"HRMv2.APIs.Skills.SkillAppService GetAll", "Trang Category > Skill" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetAll", "Trang Bonus" },
            {"HRMv2.APIs.AuditLogs.AuditLogAppService GetAllPagging", "Trang Admin > AuditLogs" },
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService GetTempEmployeeTalentPaging", "Trang Warning Employee > Plan Onboard Employee" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetListDate", "Trang Bonus" },
            {"HRMv2.APIs.DebtPaids.DebtPaidAppService GetAll", "Trang Debt" },
            {"HRMv2.APIs.Benefits.BenefitAppService GetAllBenefitsByEmployeeId", "Trang Benefit" },
            {"HRMv2.APIs.Levels.LevelAppService GetAllPaging", "Trang Category > level" },
            {"HRMv2.Users.UserAppService GetAsync", "Trang Admin > User" },
            {"HRMv2.APIs.PunishmentFunds.PunishmentFundAppService GetAllPaging", "Trang Punishment Fund" },
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService GetContractBySalaryRequest", "Trang Employee" },
            {"HRMv2.APIs.Timesheet.TimesheetAppService GetAllBanks", "Timesheet" },
            {"HRMv2.APIs.Punishments.PunishmentAppService GetListDate", "Trang Punishment" },
            {"HRMv2.APIs.Bonuses.BonusAppService GetBonusDetail", "Trang Bonus" },
            {"HRMv2.APIs.DebtPaymentPlans.DebtPaymentPlanAppService Update", "Trang Debt" },
            {"HRMv2.APIs.Benefits.BenefitAppService Create","Trang Benefit"},
            {"HRMv2.Users.UserAppService UpdateUserRole","Trang Admin > User"},
            {"HRMv2.APIs.ChangeEmployeeWorkingStatus.ChangeEmployeeWorkingStatusAppService ExtendPausing","Trang Employee"},
            {"HRMv2.APIs.Histories.HistoryAppService DeleteBranchHistory","Trang Category > Branch"},
            {"HRMv2.Web.Host.Controllers.HomeController Index","Trang Home page"},
            {"HRMv2.APIs.Debts.DebtAppService Update","Trang Debt"},
            {"HRMv2.APIs.Payslips.PayslipAppService CreatePayslipDetailBonus","Trang Payroll"},
            {"HRMv2.Authorization.Accounts.AccountAppService IsTenantAvailable","Trang Login"},
            {"HRMv2.APIs.Employees.EmployeeAppService Create","Trang Employee"},
            {"HRMv2.APIs.DebtPaids.DebtPaidAppService Create","Trang Debt"},
            {"HRMv2.Users.UserAppService CreateAsync","Trang Admin > User"},
            {"HRMv2.Controllers.TokenAuthController Authenticate","Trang login"},
            {"HRMv2.APIs.Bonuses.BonusAppService UpdateEmployeeInBonus","Trang Bonus"},
            {"HRMv2.APIs.Histories.HistoryAppService DeleteSalaryHistory","Trang Salary change request"},
            {"HRMv2.Configuration.ConfigurationAppService SetDiscordChannels","Trang Admin > Configuration"},
            {"HRMv2.APIs.Bonuses.BonusAppService Delete","Trang Bonus"},
            {"HRMv2.APIs.Payslips.PayslipAppService CreatePayslipDetailPunisment","Trang Payroll"},
            {"HRMv2.APIs.Branchs.BranchAppService Create","Trang Category > Branch"},
            {"HRMv2.APIs.Levels.LevelAppService Delete","Trang Category > Level"},
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService ApproveRequestUpdateInfo","Trang Warning Employee > Request change info"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService SendMailToOneEmployee","Trang Salary change request"},
            {"HRMv2.APIs.Branchs.BranchAppService Update","Trang Category > Branch"},
            {"HRMv2.Configuration.ConfigurationAppService CheckConnectToIMS","Trang Admin > Configuration"},
            {"HRMv2.Roles.RoleAppService ChangeRolePermission","Trang Admin > Role"},
            {"HRMv2.APIs.Payrolls.PayrollAppService ExecuatePayroll","Trang Payroll"},
            {"HRMv2.APIs.Employees.EmployeeAppService UploadAvatar","Trang Employee"},
            {"HRMv2.APIs.PunishmentTypes.PunishmentTypeAppService Delete","Trang Category > Punishment type"},
            {"HRMv2.APIs.Payrolls.PayrollAppService Update","Trang Payroll"},
            {"HRMv2.APIs.Bonuses.BonusAppService ChangeStatus","Trang Bonus"},
            {"HRMv2.Web.Host.Controllers.AntiForgeryController SetCookie",""},
            {"HRMv2.APIs.Punishments.PunishmentAppService Update","Trang Punishment"},
            {"HRMv2.APIs.Payslips.PayslipAppService ExportPayslips","Trang Payroll"},
            {"HRMv2.APIs.EmailTemplates.EmailTemplateAppService PreviewTemplate","Trang Admin > Email template"},
            {"HRMv2.Configuration.ConfigurationAppService CheckConnectToFinfast","Trang Admin > Configuration"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService AddEmployeeTosalaryRequest","Trang Salary change request"},
            {"HRMv2.Configuration.ConfigurationAppService CheckConnectWithTimesheet","Trang Admin > Configuration"},
            {"HRMv2.APIs.PunishmentFunds.PunishmentFundAppService Disburse","Trang Punishment fund"},
            {"HRMv2.APIs.Punishments.PunishmentAppService ChangeStatus","Trang Punishment"},
            {"HRMv2.Users.UserAppService UpdateUserInfo","Trang Admin > User"},
            {"HRMv2.APIs.Benefits.BenefitAppService RemoveEmployeeFromBenefit","Trang Benefit"},
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService RejectRequestUpdateInfo","Trang Warning Employee > request change info"},
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService DeleteContract","Trang Employee"},
            {"HRMv2.APIs.DebtPaids.DebtPaidAppService Update","Trang Debt"},
            {"HRMv2.APIs.Levels.LevelAppService Create","Trang Category > Level"},
            {"HRMv2.APIs.Employees.EmployeeAppService CreateEmployeeFromFile","Trang Employee"},
            {"HRMv2.APIs.Payslips.PayslipAppService ReGeneratePayslip","Trang Payroll"},
            {"HRMv2.APIs.Payrolls.PayrollAppService Create","Trang Payroll"},
            {"HRMv2.APIs.Payslips.PayslipAppService ReCalculate","Trang Payroll"},
            {"HRMv2.APIs.DebtPaymentPlans.DebtPaymentPlanAppService Delete","Trang Debt"},
            {"HRMv2.APIs.Talent.TalentAppService CreateTempEmployeeFromTalent","Trang Employee"},
            {"HRMv2.APIs.EmailTemplates.EmailTemplateAppService SendMail","Trang Admin > Email template"},
            {"HRMv2.Controllers.TokenAuthController GoogleAuthenticate","Trang login"},
            {"HRMv2.APIs.Public.PublicAppService ConfirmPayslipMail","PublicAppService"},
            {"HRMv2.Configuration.ConfigurationAppService CheckConnectToProject","Trang Admin > Configuration"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService DeleteSalaryRequestEmployee","Trang Salary change request"},
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService UploadContractFile","Trang Employee"},
            {"HRMv2.APIs.PunishmentFunds.PunishmentFundAppService Delete","Trang Punishment fund"},
            {"HRMv2.APIs.Benefits.BenefitAppService UpdateBenefitEmployee","Trang Benefit"},
            {"HRMv2.Configuration.ConfigurationAppService SetEmailSetting","Trang Admin > configuration"},
            {"HRMv2.APIs.Bonuses.BonusAppService MultipleAddEmployeeToBonus","Trang Bonus"},
            {"HRMv2.MultiTenancy.TenantAppService CreateAsync","Trang Admin > Tenant"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService UpdateRequestStatus","Trang Salary change request"},
            {"HRMv2.APIs.Payslips.PayslipAppService UpdatePayslipDetailBonus","Trang Payroll"},
            {"HRMv2.Roles.RoleAppService UpdateAsync","Trang Admin > Role"},
            {"HRMv2.APIs.Payrolls.PayrollAppService ChangeStatus","Trang Admin > Payroll"},
            {"HRMv2.APIs.EmailTemplates.EmailTemplateAppService UpdateTemplate","Trang Admin > Email template"},
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService UpdateEmployeeContract","Trang Employee"},
            {"HRMv2.APIs.Skills.SkillAppService Delete","Trang Category < Skill"},
            {"HRMv2.APIs.Payslips.PayslipAppService UpdatePayslipDeadline","Trang Payroll"},
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService DeleteContractFile","Trang Employee"},
            {"HRMv2.APIs.Punishments.PunishmentAppService IsPunishmentHasEmployee","Trang Punishment"},
            {"HRMv2.APIs.Histories.HistoryAppService DeleteWorkingHistory","Trang Employee"},
            {"HRMv2.APIs.Timesheet.TimesheetAppService UpdateAvatarFromTimesheet","Timesheet"},
            {"HRMv2.APIs.Payslips.PayslipAppService UpdatePayslipDetailPunishment","Trang Payroll"},
            {"HRMv2.APIs.Payslips.PayslipAppService ExportPayrollIncludeLastMonth","Trang Payroll"},
            {"HRMv2.APIs.JobPositions.JobPositionAppService Create","Trang Category > Job position"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService UpdateSalaryRequestemployee","Trang Salary change request"},
            {"HRMv2.APIs.JobPositions.JobPositionAppService Update","Trang Category > Job position"},
            {"HRMv2.Roles.RoleAppService DeleteAsync","Trang Admin > Role"},
            {"HRMv2.APIs.JobPositions.JobPositionAppService Delete","Trang Category > Job Position"},
            {"HRMv2.APIs.Employees.EmployeeAppService UpdateEmployeeFromFile","Trang Employee"},
            {"HRMv2.APIs.Debts.DebtAppService Create","Trang Debt"},
            {"HRMv2.APIs.Employees.EmployeeAppService Delete","Trang Employee"},
            {"HRMv2.APIs.Bonuses.BonusAppService SendMailToAllEmployee","Trang Bonus"},
            {"HRMv2.APIs.Payslips.PayslipAppService ExportTechcombank","Trang Payroll"},
            {"HRMv2.APIs.Employees.EmployeeAppService UpdateEmployeeInfoToOtherTool","Trang Employee"},
            {"HRMv2.MultiTenancy.TenantAppService DeleteAsync","Trang Admin Tenant"},
            {"HRMv2.Users.UserAppService ResetPassword","Trang Admin > user"},
            {"HRMv2.APIs.Punishments.PunishmentAppService Create","Trang Punishment"},
            {"HRMv2.APIs.Bonuses.BonusAppService ImportEmployeeToBonus","Trang Bonus"},
            {"HRMv2.APIs.Bonuses.BonusAppService Update","Trang Bonus"},
            {"HRMv2.APIs.Payslips.PayslipAppService UpdatePayslipDetail","Trang Payroll"},
            {"HRMv2.APIs.Refunds.RefundAppService Update","Trang Refund"},
            {"HRMv2.APIs.Timesheet.TimesheetAppService CreateRequestUpdateUserInfo","Timesheet"},
            {"HRMv2.APIs.Skills.SkillAppService Create","Trang Category > Skill"},
            {"HRMv2.APIs.Employees.EmployeeAppService ImportEmployeeFromFile","Trang Employee"},
            {"HRMv2.APIs.Payslips.PayslipAppService AddEmployeesToPayroll","Trang Payroll"},
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService UpdateNote","Trang Employee"},
            {"HRMv2.APIs.ProjectManagement.ProjectManagementAppService CheckConnectToProject","Project"},
            {"HRMv2.APIs.Employees.EmployeeAppService QuitJobToOtherTool","Trang Employee"},
            {"HRMv2.APIs.Payslips.PayslipAppService CreatePayslipDetail","Trang Payroll"},
            {"HRMv2.APIs.Teams.TeamAppService Create","Trang Category > Team"},
            {"HRMv2.APIs.Punishments.PunishmentAppService Delete","Trang Punishment"},
            {"HRMv2.APIs.Payrolls.PayrollAppService Delete","Trang Payroll"},
            {"HRMv2.APIs.Refunds.RefundAppService DeleteRefundEmployee","Trang Refund"},
            {"HRMv2.APIs.Branchs.BranchAppService Delete","Trang Category > Branch"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService ImportCheckpoint","Trang Salary change request"},
            {"HRMv2.APIs.Banks.BankAppService Delete","Trang Category > Bank"},
            {"HRMv2.APIs.Payslips.PayslipAppService SendMailToAllEmployee","Trang Payroll"},
            {"HRMv2.APIs.PunishmentTypes.PunishmentTypeAppService Create","Trang Category > Punishment type"},
            {"HRMv2.Roles.RoleAppService RemoveUserFromOutRole","Trang Admin > Role"},
            {"HRMv2.APIs.Employees.EmployeeAppService Test2","Trang Employee"},
            {"HRMv2.APIs.Banks.BankAppService Create","Trang Category > Bank"},
            {"HRMv2.APIs.Punishments.PunishmentAppService GeneratePunishmentsByPunishmentType","Trang Punishment"},
            {"HRMv2.APIs.Refunds.RefundAppService UpdateRefundEmployee","Trang Refund"},
            {"HRMv2.APIs.Payslips.PayslipAppService DeletePayslipDetail","Trang Payroll"},
            {"HRMv2.APIs.Employees.EmployeeAppService ExportEmployeeStatistic","Trang Employee"},
            {"HRMv2.APIs.Timesheet.TimesheetAppService ComplainPayslipMail","Timesheet"},
            {"HRMv2.APIs.Punishments.PunishmentAppService UpdatePunishmentOfEmployee","Trang Punishment"},
            {"HRMv2.APIs.BackgroundJobs.BackgroundJobAppService DeleteBackgoundJobById","Trang Admin > Background job"},
            {"HRMv2.APIs.Bonuses.BonusAppService IsBonusHasEmployee","Trang Bonus"},
            {"HRMv2.APIs.Payrolls.PayrollAppService CreateFinfastOutcomeEntry","Trang Payroll"},
            {"HRMv2.APIs.Bonuses.BonusAppService SendMailToOneEmployee","Trang Bonus"},
            {"HRMv2.APIs.Payslips.PayslipAppService ExportPayroll","Trang Payroll"},
            {"HRMv2.APIs.ChangeEmployeeWorkingStatus.ChangeEmployeeWorkingStatusAppService ExtendMaternityLeave","Trang Employee"},
            {"HRMv2.APIs.Payslips.PayslipAppService ComparePayslip","Trang Payroll"},
            {"HRMv2.APIs.ChangeEmployeeWorkingStatus.ChangeEmployeeWorkingStatusAppService ChangeStatusToPause","Trang Employee"},
            {"HRMv2.APIs.Refunds.RefundAppService DeActiveRefund","Trang Refund"},
            {"HRMv2.APIs.Debts.DebtAppService SendMailToAllEmployee","Trang Debt"},
            {"HRMv2.APIs.PunishmentFunds.PunishmentFundAppService Update","Trang Punishment fund"},
            {"HRMv2.APIs.EmployeeContracts.EmployeeContractAppService ExportContractToPDF","Trang Employee"},
            {"HRMv2.APIs.Employees.EmployeeAppService ReCreateEmployeeToOtherTool","Trang Employee"},
            {"HRMv2.APIs.Payslips.PayslipAppService GenerateAllPayslip","Trang Payroll"},
            {"HRMv2.APIs.Teams.TeamAppService AddEmployeeToTeam","Trang Category > Team"},
            {"HRMv2.APIs.Employees.EmployeeAppService ExportEmployee","Trang Employee"},
            {"HRMv2.APIs.Publics.PublicAppService CheckConnect","PublicAppService"},
            {"HRMv2.APIs.Refunds.RefundAppService Delete","Trang Refund"},
            {"HRMv2.APIs.Timesheet.TimesheetAppService ReviewInternFromTimesheet","Timesheet"},
            {"HRMv2.APIs.Benefits.BenefitAppService QuickAddEmployee","Trang Benefit"},
            {"HRMv2.APIs.DebtPaymentPlans.DebtPaymentPlanAppService GeneratePlan","Trang Debt"},
            {"HRMv2.APIs.Punishments.PunishmentAppService UpdateEmployeeInPunishment","Trang Punishment"},
            {"HRMv2.APIs.Bonuses.BonusAppService Create","Trang Bonus"},
            {"HRMv2.APIs.Bonuses.BonusAppService AddBonusForEmployee","Trang Bonus"},
            {"HRMv2.APIs.ChangeEmployeeWorkingStatus.ChangeEmployeeWorkingStatusAppService ChangeStatusToQuit","Trang Employee"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService Update","Trang Salary change request"},
            {"HRMv2.APIs.ChangeEmployeeWorkingStatus.ChangeEmployeeWorkingStatusAppService ChangeStatusToMaterityLeave","Trang Employee"},
            {"HRMv2.Configuration.ConfigurationAppService CheckConnectToTimesheet","Trang Admin > Configuration"},
            {"HRMv2.APIs.Public.PublicAppService ComplainPayslipMail","PublicAppService"},
            {"HRMv2.APIs.Payslips.PayslipAppService Delete","Trang Payroll"},
            {"HRMv2.APIs.Timesheet.TimesheetAppService ConfirmPayslipMail","Timesheet"},
            {"HRMv2.APIs.Payslips.PayslipAppService AddPunishmentIntoPayslipDetail","Trang Payroll"},
            {"HRMv2.APIs.Refunds.RefundAppService Create","Trang Refund"},
            {"HRMv2.APIs.Punishments.PunishmentAppService DeleteEmployeeFromPunishment","Trang Punishment"},
            {"HRMv2.APIs.WarningEmployees.WarningEmployeeAppService UpdateEmployeeBackDate","Trang Warning Employee > Back to work"},
            {"HRMv2.Configuration.ConfigurationAppService ChangeLoginSetting","Trang Admin > Configuration"},
            {"HRMv2.APIs.Employees.EmployeeAppService Test","Trang Employee"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService SendMailToAllEmployee","Trang Salary change request"},
            {"HRMv2.APIs.Debts.DebtAppService Delete","Trang Debt"},
            {"HRMv2.APIs.Refunds.RefundAppService AddEmployeeToRefund","Trang Refund"},
            {"HRMv2.MultiTenancy.TenantAppService UpdateAsync","Trang Admin > Tenant"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService Delete","Trang Salary change request"},
            {"HRMv2.APIs.PunishmentFunds.PunishmentFundAppService Add","Trang Punishment fund"},
            {"HRMv2.APIs.Refunds.RefundAppService ActiveRefund","Trang Refund"},
            {"HRMv2.APIs.Punishments.PunishmentAppService ImportEmployeePunishmentsFromFile","Trang Punishment"},
            {"HRMv2.APIs.Levels.LevelAppService Update","Trang Category > level"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService UpdateRequestEmployeeInfo","Trang Salary change request"},
            {"HRMv2.APIs.SalaryChangeRequests.SalaryChangeRequestAppService Create","Trang Salary change request"},
            {"HRMv2.APIs.Teams.TeamAppService Delete","Trang Category > Team"},
            {"HRMv2.APIs.Teams.TeamAppService Update","Trang Category > Team"},
            {"HRMv2.Users.UserAppService DeleteAsync","Trang Admin > User"},
            {"HRMv2.APIs.ChangeEmployeeWorkingStatus.ChangeEmployeeWorkingStatusAppService ChangeStatusToWorking","Trang Employee"},
            {"HRMv2.APIs.Punishments.PunishmentAppService AddEmployeeToPunishment","Trang Punishment"},
            {"HRMv2.Roles.RoleAppService AddUserIntoRole","Trang Admin > Role"},
            {"HRMv2.APIs.DebtPaymentPlans.DebtPaymentPlanAppService Create","Trang Debt"},
            {"HRMv2.APIs.PunishmentTypes.PunishmentTypeAppService Update","Trang Category > Punishment type"},
            {"HRMv2.Configuration.ConfigurationAppService CheckConnectToTalent","Trang Admin > Configuration"},
            {"HRMv2.APIs.Debts.DebtAppService SetDone","Trang Debt"},
            {"HRMv2.APIs.Employees.EmployeeAppService Update","Trang Employee"},
            {"HRMv2.APIs.Payslips.PayslipAppService ExportOutsideTech","Trang Payroll"},
            {"HRMv2.APIs.Payslips.PayslipAppService SendMailToOneEmployee","Trang Payroll"},
            {"HRMv2.APIs.Payslips.PayslipAppService UpdateEmployeeRemainLeaveDaysAfterCalculatingSalary","Trang Payroll"},
            {"HRMv2.APIs.DebtPaids.DebtPaidAppService Delete","Trang Debt"},
            {"HRMv2.APIs.Debts.DebtAppService SendMailToOneEmployee","Trang Debt"},
            {"HRMv2.APIs.Skills.SkillAppService Update","Trang Category > Skill"},
            {"HRMv2.APIs.Banks.BankAppService Update","Trang Category > Bank"},
            {"HRMv2.APIs.Bonuses.BonusAppService QuickAddEmployeeToBonus","Trang Bonus"},
            {"HRMv2.APIs.Talent.TalentAppService ResponseToTalent","Trang Admin > Tanent"},
            {"HRMv2.Roles.RoleAppService CreateAsync","Trang Admin > Role"},
            {"HRMv2.APIs.Employees.EmployeeAppService ChangeEmployeeBranch","Trang Employee" },
        };

        public static string GetNote(string serviceName, string methodName)
        {
            if (!Dict.ContainsKey(serviceName + " " + methodName)) return "";
            return Dict[serviceName + " " + methodName];
        }
    }
}
