name: Deploy HRMv2_BE Dev
on:
  push:
    branches:
      - dev
    paths:
    - 'aspnet-core/**'
    - '.github/workflows/deploy_server_dev_be.yml'

jobs:
  build:
    runs-on: self-hosted
    name: Build HRMv2_BE Dev
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Backup Log
        run: |
          rm -rf /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/wwwroot/swagger/
          cp -r /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/wwwroot/* /home/nccsoft/data_git/hrmv2/
          cp -r /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/App_Data/Logs/* /home/nccsoft/data_git/hrmv2/Logs/

      - name: Build Migrator
        run: |
          export PATH=$PATH:/opt/dotnet6/
          cd aspnet-core/src/HRMv2.Migrator
          dotnet6 build
          dotnet6 publish

      - name: Copy New Migrator
        run: |
          cd aspnet-core/src/HRMv2.Migrator/bin/Debug/net6.0/publish/
          rm -rf appsettings.json
          cp -r * /var/www/migrator_git/hrmv2/dev-dotnet-migrator-hrmv2/

      - name: Build Host
        run: |
          export PATH=$PATH:/opt/dotnet6/
          cd aspnet-core/src/HRMv2.Web.Host
          dotnet6 build
          dotnet6 publish

      - name: Copy New Host
        run: |
          cd aspnet-core/src/HRMv2.Web.Host/bin/Debug/net6.0/publish/
          rm -rf appsettings.json
          cp -r * /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/
    
          
  deploy:
    runs-on: self-hosted
    name: Deploy HRMv2_BE Dev
    environment: dev
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Up Data appsettings.json
        run: |
          cd aspnet-core/
          echo '${{ secrets.APP_SETTING_DEV }}' > appsettings.json

      - name: Migrate Database
        run: |
          export PATH=$PATH:/opt/dotnet6/
          sudo service erp-hrmv2-git stop
          cd aspnet-core/
          cp appsettings.json /var/www/migrator_git/hrmv2/dev-dotnet-migrator-hrmv2/
          cd /var/www/migrator_git/hrmv2/dev-dotnet-migrator-hrmv2/
          dotnet6 HRMv2.Migrator.dll -q

      - name: Restart Server
        run: |
          cd aspnet-core/
          cp appsettings.json /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/
          cd /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/
          mkdir -p /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/App_Data/Logs/
          cp -r /home/nccsoft/data_git/hrmv2/Logs/* /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/App_Data/Logs/
          cp -r /home/nccsoft/data_git/hrmv2/* /var/www/app_git/hrmv2/dev-dotnet-host-hrmv2/wwwroot/
          chmod 777 -R App_Data/
          chmod 777 -R wwwroot/
          sudo service erp-hrmv2-git start
          sudo service erp-hrmv2-git status